In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)
a

tensor([[1.5113e-38, 0.0000e+00, 1.5113e-38],
        [0.0000e+00, 1.5113e-38, 0.0000e+00]])

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.4056, 0.1777, 0.1985],
        [0.0245, 0.7884, 0.9732]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.9031, 0.4532, 0.9521],
        [0.1655, 0.4620, 0.8814]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[3616445622929465956, 6067246093671869749, 3977023933227086129],
        [6498748384004027950, 7309453675965983778, 8315168162784306286]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [20]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [21]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [22]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [23]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [24]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [25]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [26]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [27]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [28]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [29]:
# median
torch.median(e)

tensor(0.)

In [30]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [31]:
# product
torch.prod(e)

tensor(0.)

In [32]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [33]:
# variance
torch.var(e)

tensor(19.6000)

In [34]:
# argmax
torch.argmax(e)

tensor(5)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [74]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 4, 4],
        [1, 1, 2]])
tensor([[4, 7],
        [2, 5],
        [6, 1]])


In [75]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[52, 59],
        [18, 14]])

In [76]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [77]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 1],
        [4, 1],
        [4, 2]])

In [78]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[4., 5., 6.],
        [9., 2., 3.],
        [1., 0., 2.]])

In [79]:
# determinant
torch.det(h)

tensor(-71.0000)

In [80]:
# inverse
torch.inverse(h)

tensor([[-0.0563,  0.1408, -0.0423],
        [ 0.2113, -0.0282, -0.5915],
        [ 0.0282, -0.0704,  0.5211]])

### 5. Comparison operations

In [65]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6, 1, 5],
        [5, 0, 4]])
tensor([[3, 8, 8],
        [3, 3, 5]])


In [66]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [35]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [36]:
# log
torch.log(k)

tensor([[1.6094, 1.9459, 1.0986],
        [2.1972, 1.3863,   -inf]])

In [37]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 1.0966e+03, 2.0086e+01],
        [8.1031e+03, 5.4598e+01, 1.0000e+00]])

In [38]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.6458, 1.7321],
        [3.0000, 2.0000, 0.0000]])

In [39]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9991, 0.9526],
        [0.9999, 0.9820, 0.5000]])

In [40]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0180, 0.9526, 0.9526],
        [0.9820, 0.0474, 0.0474]])

In [41]:
# relu
torch.relu(k)

tensor([[5., 7., 3.],
        [9., 4., 0.]])

## Inplace Operations

In [42]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])
tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])


In [43]:
m.add_(n)

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [44]:
m

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [45]:
n

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])

In [46]:
torch.relu(m)

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [47]:
m.relu_()

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [48]:
m

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

## Copying a Tensor

In [49]:
a = torch.rand(2,3)
a

tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [50]:
b = a

In [51]:
b

tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [52]:
a[0][0] = 0

In [53]:
a

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [54]:
b

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [55]:
id(a)

136478292906192

In [56]:
id(b)

136478292906192

In [57]:
b = a.clone()

In [58]:
a

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [59]:
b

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [60]:
a[0][0] = 10

In [61]:
a

tensor([[10.0000,  0.3389,  0.6211],
        [ 0.5530,  0.6896,  0.3687]])

In [62]:
b

tensor([[0.0000, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [63]:
id(a)

136478292906192

In [64]:
id(b)

136478292905520