In [1]:
print("hi")

hi


In [3]:
#import libraries
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [6]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [7]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [8]:
# split the dataset
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-0.32195498, -1.16582351, -0.32517272, ..., -0.85807987,
        -0.76071998,  0.90337207],
       [-1.19999034,  0.00920603, -1.14664513, ..., -0.2664368 ,
        -0.45131108,  0.03790348],
       [-0.82103095,  0.11375411, -0.82058628, ..., -1.43894924,
         0.63976239, -1.02662288],
       ...,
       [ 2.5258797 ,  0.10693575,  2.45061233, ...,  1.68967268,
         0.01443073, -0.61822989],
       [ 0.59442747, -0.13397939,  0.68361009, ...,  0.88240386,
        -0.21029784,  1.19546772],
       [ 0.15738353, -1.22264312,  0.25185758, ..., -0.06446785,
        -0.11747517,  0.42628251]], shape=(455, 30))

In [11]:
X_test

array([[-0.13303921, -0.05215915, -0.10562371, ...,  0.38924151,
        -0.252638  ,  0.22668382],
       [-0.38116738, -0.65217423, -0.43576339, ..., -0.85322412,
        -0.8405149 , -1.08720569],
       [-1.19209535, -0.29534708, -1.12011969, ..., -0.24200629,
        -0.46433882,  1.73097641],
       ...,
       [ 0.76360577,  0.02284273,  0.66728674, ..., -0.46567439,
        -0.60601553, -1.32412771],
       [-1.32405443, -0.23625469, -1.31518368, ..., -0.97917019,
        -0.72489368, -0.15358144],
       [-1.11709298, -1.01809252, -1.12216011, ..., -1.3544288 ,
         1.07130638, -0.21632792]], shape=(114, 30))

In [12]:
#LabelEncoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_train.shape

(455,)

In [13]:
#Numpy array to Pytorch tensor
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

# The Dataset and DataLoader Classes

Dataset and DataLoader are core abstractions in PyTorch that decouple how you define your data from how you efficiently iterate over it in training loops.

---

## Dataset Class

The Dataset class is essentially a **blueprint**. When you create a custom Dataset, you decide how data is loaded and returned.

### Key Components

The Dataset defines three essential methods:

- **`__init__()`** → tells how data should be loaded
- **`__len__()`** → returns the total number of samples
- **`__getitem__(index)`** → returns the data (and label) at the given index

### Characteristics

The Dataset:
- Reads data from memory or disk
- Returns one sample at a time
- Does not handle batching

---

## DataLoader Class

The DataLoader wraps a Dataset and handles the heavy lifting of data iteration during training.

### Key Responsibilities

The DataLoader manages:
- **Batching** → groups samples into batches
- **Shuffling** → randomizes data order between epochs
- **Parallel loading** → uses multiple workers for faster data loading

### Important Note

The DataLoader does not store data itself. It only knows how to iterate over the Dataset efficiently.

---

## DataLoader Control Flow

Understanding how the DataLoader operates during training is crucial:

### At the Start of Each Epoch

1. **Shuffling** (if `shuffle=True`)
   - The DataLoader shuffles indices using a sampler

2. **Index Division**
   - Divides indices into chunks of `batch_size`

3. **Data Fetching**
   - For each index in the chunk, data samples are fetched from the Dataset object

4. **Batch Creation**
   - The samples are collected and combined into a batch (using `collate_fn`)

5. **Batch Return**
   - The batch is returned to the main training loop

---

## Summary

| Aspect | Dataset | DataLoader |
|--------|---------|------------|
| **Purpose** | Defines how to access individual samples | Manages efficient iteration over the Dataset |
| **Batching** | No | Yes |
| **Shuffling** | No | Yes (optional) |
| **Parallel Loading** | No | Yes (optional) |
| **Returns** | Single sample | Batch of samples |

In [17]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, feature, label):
        self.feature = feature
        self.label = label
    def __len__(self):
        return len(self.feature)
    def __getitem__(self, index):
        return self.feature[index], self.label[index]
    
     

In [18]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [19]:
train_dataset[10]

(tensor([ 1.7364, -1.1408,  1.7569,  1.8031,  0.2635,  0.5090,  1.3539,  1.4126,
         -0.0311, -0.5802,  1.1816, -0.8040,  1.1802,  1.0927,  1.3899, -0.0560,
          0.8691,  1.1091, -0.3611,  0.4739,  1.2873, -1.4481,  1.3200,  1.2027,
          0.2083, -0.3229,  0.6282,  0.7200, -0.8715, -0.4013]),
 tensor(1.))

In [20]:
# DataLoader
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [26]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [27]:
# Hyperparameters
learning_rate = 0.1
epochs = 25

In [28]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [29]:
## Training pipeline

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.16715478897094727
Epoch: 2, Loss: 0.20528551936149597
Epoch: 3, Loss: 0.07430488616228104
Epoch: 4, Loss: 0.05409431830048561
Epoch: 5, Loss: 0.06697890162467957
Epoch: 6, Loss: 0.02887369878590107
Epoch: 7, Loss: 0.11894514411687851
Epoch: 8, Loss: 0.07590161263942719
Epoch: 9, Loss: 0.31549009680747986
Epoch: 10, Loss: 0.16598443686962128
Epoch: 11, Loss: 0.16959115862846375
Epoch: 12, Loss: 0.017913049086928368
Epoch: 13, Loss: 0.6652785539627075
Epoch: 14, Loss: 0.06324651092290878
Epoch: 15, Loss: 0.07599916309118271
Epoch: 16, Loss: 0.1870088130235672
Epoch: 17, Loss: 0.07651824504137039
Epoch: 18, Loss: 0.3982279896736145
Epoch: 19, Loss: 0.4466966986656189
Epoch: 20, Loss: 0.052366580814123154
Epoch: 21, Loss: 0.1174897775053978
Epoch: 22, Loss: 0.34110626578330994
Epoch: 23, Loss: 0.03582226485013962
Epoch: 24, Loss: 0.00600298959761858
Epoch: 25, Loss: 0.07786466926336288


In [30]:
## Evaluation
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9688
