In [1]:
import torch

In [2]:
print(torch.__version__)

2.9.0+cpu


## Creating Tensor

In [3]:
# using empty
x = torch.empty(2,3)
print(x)

tensor([[-1.1697e+25,  4.4540e-41, -1.1697e+25],
        [ 4.4540e-41, -4.6217e+04,  4.4540e-41]])


In [4]:
type(x)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# rand
torch.rand(2,2)

tensor([[0.0445, 0.1309],
        [0.0995, 0.5754]])

In [12]:
# define seed to get similar number in rand
torch.manual_seed(42)
torch.rand(2,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [15]:
# using tensor
x = torch.tensor([[1,2,3],[4,5,6]])

In [14]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332]])

## Data type

In [18]:
x.dtype

torch.int64

In [20]:
torch.tensor([[1.5, 2, 3], [4, 5, 6]], dtype=torch.int64)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [24]:
x = torch.rand(2,2)
x

tensor([[0.9346, 0.5936],
        [0.8694, 0.5677]])

In [25]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.8735, 0.3523],
        [0.7559, 0.3223]])

### 2. Element wise operation

In [26]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7411, 0.4294, 0.8854],
        [0.5739, 0.2666, 0.6274]])
tensor([[0.2696, 0.4414, 0.2969],
        [0.8317, 0.1053, 0.2695]])


In [27]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2018, 0.4294, 0.2916],
        [0.5739, 0.0560, 0.0885]])

In [28]:
c = torch.tensor([1, -2, 3, -4])

In [29]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [30]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [31]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [33]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [34]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [35]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [36]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 9., 7.],
        [9., 2., 0.]])

In [39]:
#sum
torch.sum(e)
#sum along col
torch.sum(e, dim=0)
#sum along rows
torch.sum(e, dim=1)

tensor([17., 11.])

In [40]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([5.0000, 5.5000, 3.5000])

In [41]:
# median
torch.median(e)

tensor(2.)

In [42]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [43]:
# product
torch.prod(e)

tensor(0.)

In [44]:
# argmax
torch.argmax(e)

tensor(1)

### 4. Matrix operations

In [45]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 9, 3],
        [4, 9, 6]])
tensor([[2, 0],
        [6, 2],
        [7, 9]])


In [46]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 85,  45],
        [104,  72]])

In [47]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)